In [2]:
# case 1
import pandas as pd
train=pd.read_csv("train.csv")
print(train[0:7])

0         0
1         0
2         0
3         0
4         0
         ..
199995    0
199996    0
199997    0
199998    0
199999    0
Name: target, Length: 200000, dtype: int64

In [70]:
# case 2
print(train.isnull().count())

target     200000
var_0      200000
var_1      200000
var_2      200000
var_3      200000
            ...
var_195    200000
var_196    200000
var_197    200000
var_198    200000
var_199    200000
Length: 201, dtype: int64

In [60]:
# case 3
print(train.target.mean(), "\n\n")
for i in range(200):
    print(train.groupby("var_"+str(i)).target.mean())

0.10049


var_0
0.4084     0.0
0.4528     1.0
0.5979     0.0
0.8935     0.0
0.9302     0.0
          ...
19.7011    0.0
19.7379    0.0
19.9984    0.0
20.0740    0.0
20.3150    0.0
Name: target, Length: 94672, dtype: float64
var_1
-15.0434    0.0
-14.6962    0.0
-14.0910    0.0
-14.0370    1.0
-14.0325    0.0
           ...
 9.4754     0.0
 9.5119     0.0
 10.1671    0.0
 10.3356    0.0
 10.3768    0.0
Name: target, Length: 108932, dtype: float64
var_2
2.1171     0.0
2.1693     0.0
2.3134     0.0
2.5825     0.0
2.6150     0.0
          ...
18.4101    0.0
18.4127    0.0
18.6354    0.0
18.6521    0.0
19.3530    0.0
Name: target, Length: 86555, dtype: float64
var_3
-0.0402     0.0
 0.0162     0.0
 0.0430     0.0
 0.1707     0.0
 0.1788     0.0
           ...
 12.9389    0.0
 12.9773    0.0
 12.9918    0.0
 13.0983    0.0
 13.1883    0.0
Name: target, Length: 74597, dtype: float64
var_4
5.0748     0.0
5.2778     0.0
5.4902     0.0
5.5620     0.0
5.6154     0.0
          ...
15.9604    0.0
15.9914    0.0
16.0448    0.0
16.0855    0.0
16.6714    0.0
Name: target, Length: 63515, dtype: float64
var_5
-32.5626    0.0
-30.6816    0.0
-29.7773    0.0
-29.4844    0.0
-29.1883    0.0
           ...
 16.9002    0.0
 16.9073    0.0
 16.9398    0.0
 17.1281    0.0
 17.2516    0.0
Name: target, Length: 141029, dtype: float64
var_6
2.3473    0.0
2.3857    0.0
2.4957    0.0
2.4960    1.0
2.5875    0.0
         ...
8.2106    0.0
8.2852    1.0
8.3556    0.0
8.4330    0.0
8.4477    0.0
Name: target, Length: 38599, dtype: float64
var_7
5.3497     0.0
5.7494     0.0
6.4653     0.0
6.5846     0.0
6.8890     0.0
          ...
27.2227    0.0
27.3971    0.0
27.5977    0.0
27.6389    0.0
27.6918    0.0
Name: target, Length: 103063, dtype: float64
var_8
-10.5055    0.0
-10.2653    0.0
-9.9911     0.0
-9.9051     0.0
-9.8655     0.0
           ...
 9.6053     0.0
 9.6272     0.0
 9.8809     0.0
 10.1377    0.0
 10.1513    0.0
Name: target, Length: 98617, dtype: float64
var_9
3.9705     0.0
4.1624     0.0
4.1771     0.0
4.1861     1.0
4.1928     0.0
          ...
10.8274    0.0
10.8790    0.0
11.1365    0.0
11.1435    0.0
11.1506    0.0
Name: target, Length: 49417, dtype: float64
var_10
-20.7313    0.0
-19.4439    0.0
-19.4292    0.0
-18.4795    0.0
-18.3866    1.0
           ...
 17.4671    0.0
 17.4753    0.0
 17.6872    0.0
 17.7433    0.0
 18.6702    0.0
Name: target, Length: 128764, dtype: float64
var_11
-26.0950    0.0
-24.8757    0.0
-24.6355    0.0
-24.5986    0.0
-24.3415    0.0
           ...
 16.4498    0.0
 16.5137    0.0
 16.6009    0.0
 16.8517    0.0
 17.1887    1.0
Name: target, Length: 130193, dtype: float64
var_12
13.4346    0.0
13.4884    0.0
13.4921    0.0
13.4944    0.0
13.4952    0.0
          ...
14.6349    0.0
14.6364    0.0
14.6402    0.0
14.6456    0.0
14.6545    0.0
Name: target, Length: 9561, dtype: float64
var_13
-6.0111     0.0
-4.9874     0.0
-4.9661     1.0
-4.7088     0.0
-4.6816     0.0
           ...
 21.3119    0.0
 21.6165    0.0
 21.7293    0.0
 22.1980    0.0
 22.3315    0.0
Name: target, Length: 115181, dtype: float64
var_14
1.0133     1.0
1.1690     0.0
1.2167     0.0
1.2260     0.0
1.2890     0.0
          ...
14.2788    0.0
14.3050    0.0
14.3963    0.0
14.6805    0.0
14.9377    0.0
Name: target, Length: 79122, dtype: float64
var_15
13.0769    0.0
13.1852    0.0
13.2339    0.0
13.2406    0.0
13.2745    0.0
          ...
15.7416    0.0
15.7504    0.0
15.7667    0.0
15.7830    0.0
15.8633    0.0
Name: target, Length: 19810, dtype: float64
var_16
0.6351     0.0
0.6928     0.0
0.8065     0.0
0.8634     0.0
1.0289     0.0
          ...
16.8706    0.0
16.9248    0.0
17.1509    0.0
17.5501    0.0
17.9506    0.0
Name: target, Length: 86918, dtype: float64
var_17
-33.3802    0.0
-32.3297    0.0
-29.0291    0.0
-28.9739    0.0
-28.7995    0.0
           ...
 17.0953    0.0
 17.1086    0.0
 18.1670    0.0
 18.3625    0.0
 19.0259    0.0
Name: target, Length: 137823, dtype: float64
var_18
-10.6642    0.0
-9.8861     0.0
-9.2084     0.0
-8.9857     0.0
-8.8995     0.0
           ...
 38.7141    0.0
 38.8606    0.0
 38.9362    0.0
 39.8399    0.0
 41.7480    0.5
Name: target, Length: 139515, dtype: float64
var_19
-12.4025    1.0
-11.5576    0.0
-11.1649    0.0
-10.9644    1.0
-10.6596    0.0
           ...
 34.5476    0.0
 34.7128    1.0
 34.7400    0.0
 34.8237    0.0
 35.1830    0.0
Name: target, Length: 144180, dtype: float64
var_20
-5.4322     0.0
-3.3711     0.0
-3.0072     0.0
-2.8754     0.0
-2.6407     0.0
           ...
 30.4889    0.0
 30.6878    0.0
 30.8444    0.0
 30.8482    0.0
 31.2859    0.0
Name: target, Length: 127764, dtype: float64
var_21
-10.0890    0.0
-9.9406     0.0
-9.7103     0.0
-8.9563     0.0
-8.8415     0.0
           ...
 47.3066    0.0
 47.3612    0.0
 47.7823    0.0
 48.2669    0.0
 49.0443    0.0
Name: target, Length: 140062, dtype: float64
var_22
-5.3225     1.0
-5.2784     1.0
-5.1640     0.0
-5.0799     0.0
-4.8782     0.0
           ...
 13.9872    0.0
 14.0515    0.0
 14.1415    0.0
 14.3858    0.0
 14.5945    0.5
Name: target, Length: 90660, dtype: float64
var_23
1.2098    0.0
1.2442    0.0
1.2465    0.0
1.3303    0.0
1.3436    0.0
         ...
4.7607    0.0
4.7801    0.0
4.7894    1.0
4.8497    0.0
4.8752    1.0
Name: target, Length: 24913, dtype: float64
var_24
-0.6784     0.0
-0.5930     0.0
-0.5088     0.0
-0.2688     0.0
-0.2555     0.0
           ...
 22.2020    0.0
 22.2081    0.0
 23.1867    0.0
 23.5259    0.0
 25.4460    0.0
Name: target, Length: 105101, dtype: float64
var_25
12.7200    0.0
12.7260    0.0
12.7602    0.0
12.7701    0.0
12.7820    1.0
          ...
14.5779    0.0
14.5785    0.0
14.5919    0.0
14.5923    1.0
14.6546    0.0
Name: target, Length: 14853, dtype: float64
var_26
-24.2431    0.0
-24.0160    0.0
-23.8545    0.0
-23.7607    0.0
-23.6446    0.0
           ...
 13.7489    1.0
 14.7466    1.0
 15.0594    0.0
 15.4294    0.0
 15.6751    0.0
Name: target, Length: 127089, dtype: float64
var_27
-6.1668    0.0
-5.9869    0.0
-5.9142    0.0
-5.7133    0.0
-5.7097    0.0
          ...
 2.9253    0.0
 2.9374    1.0
 2.9729    0.0
 3.0452    0.0
 3.2431    0.0
Name: target, Length: 60185, dtype: float64
var_28
2.0896    0.0
2.7989    0.0
2.8352    0.0
2.9063    0.0
2.9177    0.0
         ...
8.3647    0.0
8.4764    0.0
8.5543    0.0
8.6604    0.0
8.7874    0.0
Name: target, Length: 35859, dtype: float64
var_29
-4.7872     0.0
-4.3053     0.0
-4.0197     1.0
-3.9292     0.0
-3.8568     0.0
           ...
 12.6230    0.0
 12.7810    1.0
 12.8909    0.0
 13.1257    0.0
 13.1431    0.0
Name: target, Length: 88339, dtype: float64
var_30
-34.7984    0.0
-33.5249    0.0
-32.8542    0.0
-32.8506    0.0
-32.7813    0.0
           ...
 14.2360    0.0
 14.3166    0.0
 14.9009    0.0
 15.1345    0.0
 15.6515    0.0
Name: target, Length: 145977, dtype: float64
var_31
2.1406     0.0
2.2642     0.0
2.3398     0.0
2.5031     0.0
2.5137     0.0
          ...
18.7017    0.0
18.8397    0.0
18.8764    0.0
20.0471    0.0
20.1719    0.0
Name: target, Length: 77388, dtype: float64
var_32
-8.9861    0.0
-8.9435    0.0
-8.3913    0.0
-8.2818    0.0
-8.2016    0.0
          ...
 6.5732    1.0
 6.6202    1.0
 6.6964    0.0
 6.7074    0.0
 6.7871    0.0
Name: target, Length: 85964, dtype: float64
var_33
1.5085     0.0
1.8655     0.0
1.9055     0.0
2.0000     0.0
2.1111     1.0
          ...
27.9776    0.0
28.0725    1.0
28.1054    0.0
29.0772    1.0
29.5466    0.0
Name: target, Length: 112239, dtype: float64
var_34
9.8169     0.0
9.8238     0.0
9.8369     0.0
9.8425     0.0
9.8805     0.0
          ...
13.1213    0.5
13.1346    1.0
13.1525    0.0
13.1603    0.0
13.2878    0.0
Name: target, Length: 25164, dtype: float64
var_35
-16.5136    0.0
-15.0152    0.0
-14.8186    0.0
-14.6887    0.0
-14.5918    1.0
           ...
 19.9431    0.0
 20.2390    0.0
 20.2801    0.0
 20.3823    0.0
 21.5289    0.0
Name: target, Length: 122384, dtype: float64
var_36
-8.0951     0.0
-8.0425     0.0
-7.9080     0.0
-7.7918     0.0
-7.7657     0.0
           ...
 13.1496    1.0
 13.2307    0.0
 13.2838    0.0
 13.5784    0.0
 14.2456    0.0
Name: target, Length: 96404, dtype: float64
var_37
-1.1834     0.0
-0.8878     0.0
-0.7772     0.0
-0.7315     0.0
-0.7130     0.0
           ...
 11.5827    0.0
 11.5988    0.0
 11.6826    0.0
 11.7726    0.0
 11.8638    0.0
Name: target, Length: 79040, dtype: float64
var_38
-6.3371     1.0
-5.9082     0.0
-4.8754     0.0
-4.5561     0.0
-4.1627     0.0
           ...
 27.1609    0.0
 27.2531    1.0
 27.6277    0.0
 28.6329    0.0
 29.8235    1.0
Name: target, Length: 115366, dtype: float64
var_39
-14.5457    0.0
-13.9863    0.0
-13.7372    0.0
-13.7258    0.0
-13.6501    1.0
           ...
 14.6076    0.0
 14.7115    0.0
 14.7317    0.0
 15.1409    0.0
 15.3223    0.0
Name: target, Length: 112674, dtype: float64
var_40
-35.2117    0.0
-35.2029    0.0
-34.1895    0.0
-33.7805    0.0
-33.5438    0.0
           ...
 16.4429    0.0
 16.6694    0.0
 16.7994    1.0
 17.6696    0.0
 18.1056    0.0
Name: target, Length: 141878, dtype: float64
var_41
-8.5359     0.0
-7.8237     0.0
-7.6563     0.0
-7.4439     0.0
-7.4212     0.0
           ...
 25.0401    0.0
 25.2819    0.0
 25.3231    0.0
 25.3470    0.0
 26.1658    0.0
Name: target, Length: 131896, dtype: float64
var_42
8.8590     0.0
8.9648     0.0
8.9658     0.0
8.9913     0.0
9.0039     0.0
          ...
13.3039    1.0
13.3551    0.0
13.4123    0.0
13.4313    0.0
13.4696    0.0
Name: target, Length: 31592, dtype: float64
var_43
10.6528    0.0
10.6571    0.0
10.6861    0.0
10.6954    0.0
10.7124    0.0
          ...
12.5468    0.0
12.5659    0.0
12.5678    0.0
12.5771    0.0
12.5779    0.0
Name: target, Length: 15188, dtype: float64
var_44
-9.9396     0.0
-9.6796     1.0
-9.5916     0.0
-9.4533     0.0
-9.2224     0.0
           ...
 28.7770    0.0
 29.1918    0.0
 29.3291    0.0
 29.6690    1.0
 34.1961    0.0
Name: target, Length: 127702, dtype: float64
var_45
-90.2525    0.0
-83.1075    0.0
-82.2573    0.0
-82.1271    0.0
-81.4005    0.0
           ...
 57.2067    0.0
 59.3348    0.0
 59.5831    0.0
 61.0190    0.0
 62.0844    0.0
Name: target, Length: 169968, dtype: float64
var_46
1.2062     0.0
1.8350     0.0
1.8986     0.0
2.0119     0.0
2.0219     0.0
          ...
20.7862    0.0
20.8070    0.0
20.8680    0.0
21.0807    0.0
21.2939    0.0
Name: target, Length: 93450, dtype: float64
var_47
-47.6862    0.0
-44.3220    0.0
-44.3122    0.0
-43.9447    0.0
-43.6827    0.0
           ...
 18.7334    0.0
 19.1162    0.0
 19.4466    0.0
 19.6435    0.0
 20.6854    0.0
Name: target, Length: 154781, dtype: float64
var_48
-23.9022    0.0
-23.8044    0.0
-23.4164    0.0
-22.9464    0.0
-22.7633    0.0
           ...
 52.3327    0.0
 53.0858    0.0
 53.4915    0.0
 53.7268    0.0
 54.2738    0.0
Name: target, Length: 152039, dtype: float64
var_49
-8.0707     0.0
-7.6722     0.0
-7.3199     0.0
-6.9777     0.0
-6.6859     0.0
           ...
 40.2719    0.0
 40.4065    0.0
 40.7122    0.0
 40.7367    0.0
 41.1530    0.0
Name: target, Length: 140641, dtype: float64
var_50
10.3855    0.0
10.5073    0.0
10.5081    0.0
10.5716    0.0
10.6113    0.0
          ...
15.2288    0.0
15.2430    0.0
15.2675    0.0
15.3154    0.0
15.3172    0.0
Name: target, Length: 32308, dtype: float64
var_51
-15.0462    0.0
-13.2473    0.5
-12.7371    0.0
-12.6764    0.0
-12.3948    1.0
           ...
 39.0405    1.0
 39.0710    0.0
 39.5006    0.5
 39.5800    0.0
 40.6890    1.0
Name: target, Length: 143455, dtype: float64
var_52
-24.7214    0.0
-22.4266    0.0
-21.1311    0.0
-20.9729    1.0
-20.7723    0.0
           ...
 14.2165    0.0
 14.8029    0.0
 15.3592    0.0
 15.9695    0.0
 17.0968    0.0
Name: target, Length: 121313, dtype: float64
var_53
3.3449    0.0
3.3988    0.0
3.4413    0.0
3.4834    0.0
3.5119    0.0
         ...
7.9907    0.0
8.0609    0.0
8.0861    0.0
8.0917    0.0
8.2315    0.0
Name: target, Length: 33460, dtype: float64
var_54
-26.7786    0.0
-25.5947    0.0
-25.4808    0.0
-25.3379    0.0
-25.0561    0.0
           ...
 27.7315    0.0
 27.8876    0.0
 28.1997    0.0
 28.4404    0.0
 28.5724    0.0
Name: target, Length: 144776, dtype: float64
var_55
-3.7826     0.0
-3.5068     0.0
-3.0330     0.0
-3.0123     0.0
-3.0056     0.0
           ...
 28.4303    0.0
 28.4570    0.0
 28.5044    0.0
 28.7961    0.0
 29.0921    0.0
Name: target, Length: 128077, dtype: float64
var_56
2.7618     0.0
3.4762     0.0
3.9277     0.5
4.0516     0.0
4.1274     0.0
          ...
27.7018    0.0
27.7964    0.0
27.9746    0.0
28.0648    0.0
29.0741    0.0
Name: target, Length: 103045, dtype: float64
var_57
3.4423    0.0
3.5258    0.0
3.6119    0.0
3.6364    0.0
3.6964    0.0
         ...
9.0164    0.0
9.0244    0.0
9.0422    0.0
9.1174    0.0
9.1609    1.0
Name: target, Length: 35545, dtype: float64
var_58
-12.6009    1.0
-11.6315    0.0
-11.6034    0.0
-11.5903    0.0
-11.4144    0.0
           ...
 19.3922    0.0
 19.4598    0.0
 19.6816    0.0
 19.7091    0.0
 20.4833    0.0
Name: target, Length: 113907, dtype: float64
var_59
6.1840     0.0
6.3959     0.0
6.5184     1.0
6.5563     0.0
6.5923     0.0
          ...
11.7678    0.0
11.8431    0.0
11.8722    0.0
11.9182    0.0
11.9867    0.0
Name: target, Length: 37744, dtype: float64
var_60
-2.1006     0.0
-0.8519     0.0
-0.8176     0.0
-0.4902     0.0
-0.3143     0.0
           ...
 24.3164    0.0
 24.3264    0.0
 24.3757    0.0
 24.4149    0.0
 25.1955    0.0
Name: target, Length: 113763, dtype: float64
var_61
-48.8027    0.0
-47.7779    0.0
-47.6819    0.0
-47.3058    0.0
-46.9988    0.0
           ...
 26.4445    0.0
 26.5738    0.0
 26.9009    0.0
 26.9723    0.0
 27.1029    0.0
Name: target, Length: 159369, dtype: float64
var_62
-6.3289    0.0
-6.1491    0.0
-6.0988    0.0
-6.0510    0.0
-5.9505    0.0
          ...
 7.3024    0.0
 7.3825    0.0
 7.4070    0.0
 7.6402    0.0
 7.7536    1.0
Name: target, Length: 74777, dtype: float64
var_63
-10.5544    0.0
-10.4517    0.0
-10.4068    0.5
-10.2842    0.0
-10.2766    1.0
           ...
 9.9711     0.0
 10.1176    0.0
 10.3921    0.0
 10.6380    0.0
 11.2317    0.0
Name: target, Length: 97098, dtype: float64
var_64
1.6117     0.0
1.7240     0.0
1.7679     0.0
1.8275     0.0
1.8490     0.0
          ...
10.8719    0.0
10.9404    0.0
10.9492    0.0
10.9749    0.0
11.1537    0.0
Name: target, Length: 59379, dtype: float64
var_65
-14.0888    0.0
-13.7212    0.0
-13.6193    0.0
-13.4690    0.0
-12.7267    1.0
           ...
 13.6304    1.0
 13.6414    0.0
 13.9544    0.0
 14.2107    0.0
 15.7313    0.0
Name: target, Length: 108347, dtype: float64
var_66
1.3368    0.0
1.7539    0.0
2.0337    0.0
2.0936    0.0
2.1184    0.0
         ...
9.5461    0.0
9.6029    0.0
9.6188    0.0
9.6190    0.0
9.7132    0.0
Name: target, Length: 47722, dtype: float64
var_67
-19.5443    0.0
-17.7479    0.0
-16.9958    0.0
-16.8936    0.0
-16.3353    0.0
           ...
 37.4376    0.0
 37.4745    0.0
 37.8539    0.0
 39.3056    0.0
 39.3968    0.0
Name: target, Length: 137253, dtype: float64
var_68
4.9938    0.0
4.9951    0.0
4.9964    0.0
4.9967    0.0
4.9976    0.0
         ...
5.0438    0.0
5.0444    0.0
5.0445    0.0
5.0458    0.0
5.0469    0.0
Name: target, Length: 451, dtype: float64
var_69
-16.3094    0.0
-16.0995    0.0
-16.0486    0.0
-15.8873    0.0
-15.6624    0.0
           ...
 7.9651     0.0
 8.1057     0.0
 8.2595     0.0
 8.4753     0.0
 8.5473     0.0
Name: target, Length: 110346, dtype: float64
var_70
-17.0275    0.0
-15.9349    0.0
-15.3447    0.0
-12.3791    0.0
-11.5493    0.0
           ...
 59.9496    0.0
 60.9406    0.0
 61.1035    0.0
 63.3869    0.0
 64.4644    0.0
Name: target, Length: 153193, dtype: float64
var_71
-0.2240    1.0
-0.2201    0.0
-0.2179    0.0
-0.1841    0.0
-0.1583    0.0
          ...
 1.5074    0.0
 1.5124    0.0
 1.5155    0.0
 1.5354    0.0
 1.5719    1.0
Name: target, Length: 13527, dtype: float64
var_72
-12.3834    0.0
-11.8723    0.0
-11.5645    0.0
-11.5538    0.0
-11.5101    0.0
           ...
 13.7635    0.0
 13.8199    0.0
 13.9879    0.0
 14.1246    0.0
 14.1500    0.0
Name: target, Length: 110114, dtype: float64
var_73
-1.6658     0.0
-1.1343     0.0
-1.0664     0.0
-0.9671     0.0
-0.8426     0.0
           ...
 43.4268    0.0
 43.4961    0.0
 43.5986    0.0
 44.2137    0.0
 44.5361    0.0
Name: target, Length: 142582, dtype: float64
var_74
-34.1015    0.0
-32.8139    0.0
-31.7786    0.0
-31.6474    0.0
-31.5289    0.0
           ...
 67.5137    0.0
 68.4055    0.0
 68.5778    0.0
 69.5024    0.0
 70.2720    0.0
Name: target, Length: 161058, dtype: float64
var_75
-1.2936     0.0
-0.6909     0.0
-0.6628     0.0
-0.5288     0.0
-0.3475     0.0
           ...
 35.6206    0.0
 35.6223    0.0
 35.6242    0.0
 35.9075    0.0
 36.1567    0.0
Name: target, Length: 129383, dtype: float64
var_76
-21.6333    1.0
-20.9244    0.0
-20.3150    0.0
-19.7271    0.0
-19.3773    0.0
           ...
 33.0702    0.0
 33.5674    0.0
 34.0951    0.0
 34.4007    0.0
 34.4352    0.0
Name: target, Length: 139317, dtype: float64
var_77
7.4257     0.0
7.7820     0.0
7.8664     0.0
8.0724     1.0
8.4330     0.0
          ...
30.6091    0.0
30.6137    0.0
30.6215    0.0
30.6240    0.0
30.9569    0.0
Name: target, Length: 106809, dtype: float64
var_78
-1.8183     0.0
-1.2542     0.0
-0.7483     0.0
-0.7372     1.0
-0.6964     0.0
           ...
 11.2024    1.0
 11.2183    0.0
 11.2640    0.0
 11.3047    0.5
 11.3507    0.0
Name: target, Length: 72254, dtype: float64
var_79
10.4454    0.0
10.4724    0.0
10.4767    0.0
10.5191    0.0
10.5508    0.0
          ...
18.1112    0.0
18.1210    1.0
18.1460    0.0
18.1787    0.0
18.2256    1.0
Name: target, Length: 53212, dtype: float64
var_80
-18.0422    0.0
-17.0927    0.0
-16.9501    0.0
-16.7045    1.0
-15.8762    0.0
           ...
 29.1762    0.0
 29.3029    0.0
 29.9658    0.0
 30.2443    0.0
 30.4769    0.0
Name: target, Length: 136432, dtype: float64
var_81
7.5865     0.0
7.5938     0.0
7.9972     1.0
8.0189     0.0
8.0248     0.0
          ...
22.7227    0.0
22.8002    0.0
22.8704    0.0
22.9300    0.0
23.1324    0.0
Name: target, Length: 79065, dtype: float64
var_82
-30.0266    0.0
-29.8825    0.0
-29.1308    0.0
-28.9814    0.0
-28.7124    0.0
           ...
 19.2717    0.0
 19.2787    0.0
 19.7049    0.0
 21.2560    1.0
 21.8934    0.0
Name: target, Length: 144829, dtype: float64
var_83
-24.2201    0.0
-22.6955    0.0
-22.1452    0.0
-22.0743    0.0
-21.5471    0.0
           ...
 26.0673    0.0
 26.3562    1.0
 26.6568    0.0
 26.9660    0.0
 27.7143    0.0
Name: target, Length: 144281, dtype: float64
var_84
-24.4398    0.0
-23.7057    0.0
-23.3423    0.0
-23.2112    1.0
-23.1971    0.0
           ...
 15.6506    0.0
 15.6798    0.0
 16.4966    0.0
 16.7575    1.0
 17.7424    0.0
Name: target, Length: 133766, dtype: float64
var_85
7.0230     0.0
7.5132     0.0
7.5869     0.0
7.6969     0.0
7.7679     0.0
          ...
30.0117    0.0
30.7450    0.0
30.9763    0.0
31.0172    0.0
32.9011    0.0
Name: target, Length: 108437, dtype: float64
var_86
-19.2722    0.0
-19.1327    1.0
-18.1250    0.0
-17.9972    0.0
-16.9755    0.0
           ...
 31.7867    0.0
 31.8550    0.0
 33.0470    0.0
 34.2731    0.0
 34.5637    0.0
Name: target, Length: 140594, dtype: float64
var_87
-8.4816     0.0
-7.9925     0.0
-7.9873     0.0
-7.8775     0.0
-7.3634     0.0
           ...
 31.6000    0.0
 32.0732    0.0
 32.0990    0.0
 32.7761    0.0
 33.3541    0.5
Name: target, Length: 125296, dtype: float64
var_88
1.3502     1.0
1.5868     0.0
1.8688     0.0
1.9595     0.0
1.9655     0.0
          ...
16.6540    0.0
16.7177    0.0
16.8911    0.0
17.2686    0.0
17.4594    0.0
Name: target, Length: 84918, dtype: float64
var_89
-9.6014     1.0
-8.5319     0.0
-8.3123     0.0
-8.0283     0.0
-7.9863     0.0
           ...
 13.8215    1.0
 13.8636    0.0
 14.5926    0.0
 15.1006    0.0
 15.4816    0.0
Name: target, Length: 103522, dtype: float64
var_90
-61.7180    0.0
-60.1899    0.0
-60.1727    0.0
-59.7720    0.0

In [67]:
# case 4
print(train.target.count(), "\n\n")
for i in range(200):
    print(train.groupby("var_"+str(i)).target.count())

200000


var_0
0.4084     1
0.4528     1
0.5979     1
0.8935     1
0.9302     1
          ..
19.7011    1
19.7379    1
19.9984    1
20.0740    1
20.3150    2
Name: target, Length: 94672, dtype: int64
var_1
-15.0434    1
-14.6962    1
-14.0910    1
-14.0370    1
-14.0325    1
           ..
 9.4754     1
 9.5119     1
 10.1671    2
 10.3356    2
 10.3768    1
Name: target, Length: 108932, dtype: int64
var_2
2.1171     1
2.1693     1
2.3134     1
2.5825     1
2.6150     1
          ..
18.4101    1
18.4127    1
18.6354    1
18.6521    1
19.3530    1
Name: target, Length: 86555, dtype: int64
var_3
-0.0402     1
 0.0162     1
 0.0430     1
 0.1707     1
 0.1788     1
           ..
 12.9389    1
 12.9773    1
 12.9918    1
 13.0983    1
 13.1883    1
Name: target, Length: 74597, dtype: int64
var_4
5.0748     1
5.2778     1
5.4902     1
5.5620     1
5.6154     1
          ..
15.9604    1
15.9914    1
16.0448    1
16.0855    1
16.6714    1
Name: target, Length: 63515, dtype: int64
var_5
-32.5626    1
-30.6816    1
-29.7773    1
-29.4844    1
-29.1883    1
           ..
 16.9002    1
 16.9073    1
 16.9398    1
 17.1281    1
 17.2516    1
Name: target, Length: 141029, dtype: int64
var_6
2.3473    1
2.3857    1
2.4957    1
2.4960    1
2.5875    1
         ..
8.2106    1
8.2852    1
8.3556    1
8.4330    1
8.4477    1
Name: target, Length: 38599, dtype: int64
var_7
5.3497     1
5.7494     1
6.4653     1
6.5846     1
6.8890     1
          ..
27.2227    1
27.3971    1
27.5977    1
27.6389    1
27.6918    1
Name: target, Length: 103063, dtype: int64
var_8
-10.5055    1
-10.2653    1
-9.9911     1
-9.9051     1
-9.8655     1
           ..
 9.6053     1
 9.6272     1
 9.8809     1
 10.1377    1
 10.1513    1
Name: target, Length: 98617, dtype: int64
var_9
3.9705     1
4.1624     1
4.1771     1
4.1861     1
4.1928     2
          ..
10.8274    2
10.8790    1
11.1365    1
11.1435    1
11.1506    1
Name: target, Length: 49417, dtype: int64
var_10
-20.7313    1
-19.4439    1
-19.4292    1
-18.4795    1
-18.3866    1
           ..
 17.4671    1
 17.4753    1
 17.6872    1
 17.7433    1
 18.6702    1
Name: target, Length: 128764, dtype: int64
var_11
-26.0950    1
-24.8757    2
-24.6355    1
-24.5986    1
-24.3415    1
           ..
 16.4498    1
 16.5137    1
 16.6009    1
 16.8517    1
 17.1887    1
Name: target, Length: 130193, dtype: int64
var_12
13.4346    1
13.4884    1
13.4921    1
13.4944    1
13.4952    2
          ..
14.6349    1
14.6364    1
14.6402    1
14.6456    1
14.6545    1
Name: target, Length: 9561, dtype: int64
var_13
-6.0111     1
-4.9874     1
-4.9661     1
-4.7088     1
-4.6816     1
           ..
 21.3119    1
 21.6165    1
 21.7293    1
 22.1980    1
 22.3315    1
Name: target, Length: 115181, dtype: int64
var_14
1.0133     1
1.1690     1
1.2167     1
1.2260     1
1.2890     1
          ..
14.2788    1
14.3050    1
14.3963    1
14.6805    1
14.9377    1
Name: target, Length: 79122, dtype: int64
var_15
13.0769    1
13.1852    1
13.2339    1
13.2406    2
13.2745    1
          ..
15.7416    1
15.7504    1
15.7667    1
15.7830    1
15.8633    1
Name: target, Length: 19810, dtype: int64
var_16
0.6351     1
0.6928     1
0.8065     1
0.8634     1
1.0289     1
          ..
16.8706    1
16.9248    1
17.1509    1
17.5501    1
17.9506    1
Name: target, Length: 86918, dtype: int64
var_17
-33.3802    1
-32.3297    1
-29.0291    1
-28.9739    1
-28.7995    1
           ..
 17.0953    1
 17.1086    1
 18.1670    1
 18.3625    1
 19.0259    1
Name: target, Length: 137823, dtype: int64
var_18
-10.6642    1
-9.8861     1
-9.2084     1
-8.9857     1
-8.8995     1
           ..
 38.7141    1
 38.8606    2
 38.9362    1
 39.8399    1
 41.7480    2
Name: target, Length: 139515, dtype: int64
var_19
-12.4025    1
-11.5576    1
-11.1649    1
-10.9644    1
-10.6596    1
           ..
 34.5476    1
 34.7128    1
 34.7400    1
 34.8237    1
 35.1830    1
Name: target, Length: 144180, dtype: int64
var_20
-5.4322     1
-3.3711     1
-3.0072     1
-2.8754     2
-2.6407     1
           ..
 30.4889    1
 30.6878    1
 30.8444    1
 30.8482    2
 31.2859    1
Name: target, Length: 127764, dtype: int64
var_21
-10.0890    1
-9.9406     1
-9.7103     1
-8.9563     1
-8.8415     1
           ..
 47.3066    1
 47.3612    1
 47.7823    1
 48.2669    1
 49.0443    2
Name: target, Length: 140062, dtype: int64
var_22
-5.3225     1
-5.2784     1
-5.1640     1
-5.0799     1
-4.8782     1
           ..
 13.9872    1
 14.0515    1
 14.1415    1
 14.3858    1
 14.5945    2
Name: target, Length: 90660, dtype: int64
var_23
1.2098    1
1.2442    1
1.2465    1
1.3303    1
1.3436    1
         ..
4.7607    1
4.7801    1
4.7894    1
4.8497    1
4.8752    1
Name: target, Length: 24913, dtype: int64
var_24
-0.6784     1
-0.5930     1
-0.5088     1
-0.2688     1
-0.2555     1
           ..
 22.2020    1
 22.2081    1
 23.1867    1
 23.5259    2
 25.4460    1
Name: target, Length: 105101, dtype: int64
var_25
12.7200    1
12.7260    1
12.7602    1
12.7701    1
12.7820    1
          ..
14.5779    1
14.5785    1
14.5919    1
14.5923    1
14.6546    1
Name: target, Length: 14853, dtype: int64
var_26
-24.2431    1
-24.0160    1
-23.8545    1
-23.7607    1
-23.6446    1
           ..
 13.7489    1
 14.7466    1
 15.0594    1
 15.4294    1
 15.6751    1
Name: target, Length: 127089, dtype: int64
var_27
-6.1668    1
-5.9869    1
-5.9142    1
-5.7133    1
-5.7097    1
          ..
 2.9253    1
 2.9374    1
 2.9729    1
 3.0452    1
 3.2431    1
Name: target, Length: 60185, dtype: int64
var_28
2.0896    1
2.7989    1
2.8352    2
2.9063    1
2.9177    1
         ..
8.3647    1
8.4764    1
8.5543    1
8.6604    1
8.7874    1
Name: target, Length: 35859, dtype: int64
var_29
-4.7872     1
-4.3053     1
-4.0197     1
-3.9292     1
-3.8568     1
           ..
 12.6230    1
 12.7810    1
 12.8909    1
 13.1257    1
 13.1431    1
Name: target, Length: 88339, dtype: int64
var_30
-34.7984    1
-33.5249    1
-32.8542    1
-32.8506    1
-32.7813    1
           ..
 14.2360    1
 14.3166    1
 14.9009    1
 15.1345    1
 15.6515    1
Name: target, Length: 145977, dtype: int64
var_31
2.1406     1
2.2642     1
2.3398     1
2.5031     1
2.5137     1
          ..
18.7017    1
18.8397    1
18.8764    1
20.0471    1
20.1719    1
Name: target, Length: 77388, dtype: int64
var_32
-8.9861    1
-8.9435    1
-8.3913    1
-8.2818    1
-8.2016    1
          ..
 6.5732    1
 6.6202    1
 6.6964    1
 6.7074    1
 6.7871    1
Name: target, Length: 85964, dtype: int64
var_33
1.5085     1
1.8655     1
1.9055     1
2.0000     1
2.1111     1
          ..
27.9776    2
28.0725    1
28.1054    1
29.0772    1
29.5466    1
Name: target, Length: 112239, dtype: int64
var_34
9.8169     1
9.8238     1
9.8369     1
9.8425     1
9.8805     1
          ..
13.1213    2
13.1346    1
13.1525    1
13.1603    1
13.2878    1
Name: target, Length: 25164, dtype: int64
var_35
-16.5136    1
-15.0152    1
-14.8186    1
-14.6887    1
-14.5918    1
           ..
 19.9431    1
 20.2390    1
 20.2801    1
 20.3823    2
 21.5289    1
Name: target, Length: 122384, dtype: int64
var_36
-8.0951     1
-8.0425     1
-7.9080     1
-7.7918     1
-7.7657     1
           ..
 13.1496    1
 13.2307    1
 13.2838    1
 13.5784    1
 14.2456    1
Name: target, Length: 96404, dtype: int64
var_37
-1.1834     1
-0.8878     1
-0.7772     1
-0.7315     1
-0.7130     1
           ..
 11.5827    1
 11.5988    1
 11.6826    1
 11.7726    1
 11.8638    1
Name: target, Length: 79040, dtype: int64
var_38
-6.3371     1
-5.9082     1
-4.8754     1
-4.5561     1
-4.1627     1
           ..
 27.1609    1
 27.2531    1
 27.6277    1
 28.6329    1
 29.8235    1
Name: target, Length: 115366, dtype: int64
var_39
-14.5457    1
-13.9863    1
-13.7372    1
-13.7258    1
-13.6501    1
           ..
 14.6076    1
 14.7115    1
 14.7317    1
 15.1409    1
 15.3223    1
Name: target, Length: 112674, dtype: int64
var_40
-35.2117    1
-35.2029    1
-34.1895    1
-33.7805    1
-33.5438    1
           ..
 16.4429    1
 16.6694    1
 16.7994    1
 17.6696    1
 18.1056    2
Name: target, Length: 141878, dtype: int64
var_41
-8.5359     1
-7.8237     1
-7.6563     1
-7.4439     1
-7.4212     1
           ..
 25.0401    1
 25.2819    1
 25.3231    2
 25.3470    1
 26.1658    1
Name: target, Length: 131896, dtype: int64
var_42
8.8590     1
8.9648     1
8.9658     1
8.9913     1
9.0039     1
          ..
13.3039    1
13.3551    1
13.4123    1
13.4313    1
13.4696    1
Name: target, Length: 31592, dtype: int64
var_43
10.6528    1
10.6571    1
10.6861    1
10.6954    1
10.7124    1
          ..
12.5468    1
12.5659    1
12.5678    1
12.5771    1
12.5779    1
Name: target, Length: 15188, dtype: int64
var_44
-9.9396     1
-9.6796     2
-9.5916     1
-9.4533     1
-9.2224     1
           ..
 28.7770    1
 29.1918    1
 29.3291    1
 29.6690    1
 34.1961    1
Name: target, Length: 127702, dtype: int64
var_45
-90.2525    1
-83.1075    1
-82.2573    1
-82.1271    1
-81.4005    1
           ..
 57.2067    1
 59.3348    1
 59.5831    1
 61.0190    1
 62.0844    1
Name: target, Length: 169968, dtype: int64
var_46
1.2062     1
1.8350     1
1.8986     1
2.0119     1
2.0219     1
          ..
20.7862    1
20.8070    1
20.8680    1
21.0807    1
21.2939    1
Name: target, Length: 93450, dtype: int64
var_47
-47.6862    1
-44.3220    1
-44.3122    1
-43.9447    1
-43.6827    1
           ..
 18.7334    1
 19.1162    1
 19.4466    1
 19.6435    1
 20.6854    1
Name: target, Length: 154781, dtype: int64
var_48
-23.9022    1
-23.8044    1
-23.4164    1
-22.9464    1
-22.7633    1
           ..
 52.3327    1
 53.0858    1
 53.4915    1
 53.7268    1
 54.2738    1
Name: target, Length: 152039, dtype: int64
var_49
-8.0707     1
-7.6722     1
-7.3199     1
-6.9777     1
-6.6859     1
           ..
 40.2719    1
 40.4065    1
 40.7122    1
 40.7367    1
 41.1530    1
Name: target, Length: 140641, dtype: int64
var_50
10.3855    1
10.5073    1
10.5081    1
10.5716    1
10.6113    1
          ..
15.2288    1
15.2430    1
15.2675    1
15.3154    1
15.3172    1
Name: target, Length: 32308, dtype: int64
var_51
-15.0462    1
-13.2473    2
-12.7371    1
-12.6764    1
-12.3948    1
           ..
 39.0405    1
 39.0710    1
 39.5006    2
 39.5800    1
 40.6890    1
Name: target, Length: 143455, dtype: int64
var_52
-24.7214    1
-22.4266    1
-21.1311    1
-20.9729    1
-20.7723    1
           ..
 14.2165    1
 14.8029    1
 15.3592    1
 15.9695    1
 17.0968    1
Name: target, Length: 121313, dtype: int64
var_53
3.3449    1
3.3988    1
3.4413    2
3.4834    1
3.5119    1
         ..
7.9907    2
8.0609    1
8.0861    1
8.0917    1
8.2315    1
Name: target, Length: 33460, dtype: int64
var_54
-26.7786    1
-25.5947    1
-25.4808    1
-25.3379    1
-25.0561    1
           ..
 27.7315    1
 27.8876    1
 28.1997    1
 28.4404    1
 28.5724    1
Name: target, Length: 144776, dtype: int64
var_55
-3.7826     1
-3.5068     1
-3.0330     2
-3.0123     1
-3.0056     1
           ..
 28.4303    1
 28.4570    1
 28.5044    1
 28.7961    1
 29.0921    1
Name: target, Length: 128077, dtype: int64
var_56
2.7618     1
3.4762     1
3.9277     2
4.0516     1
4.1274     1
          ..
27.7018    1
27.7964    1
27.9746    1
28.0648    1
29.0741    1
Name: target, Length: 103045, dtype: int64
var_57
3.4423    1
3.5258    1
3.6119    1
3.6364    1
3.6964    1
         ..
9.0164    1
9.0244    1
9.0422    1
9.1174    1
9.1609    1
Name: target, Length: 35545, dtype: int64
var_58
-12.6009    1
-11.6315    1
-11.6034    1
-11.5903    1
-11.4144    1
           ..
 19.3922    1
 19.4598    1
 19.6816    1
 19.7091    1
 20.4833    1
Name: target, Length: 113907, dtype: int64
var_59
6.1840     1
6.3959     1
6.5184     1
6.5563     1
6.5923     1
          ..
11.7678    1
11.8431    1
11.8722    2
11.9182    1
11.9867    1
Name: target, Length: 37744, dtype: int64
var_60
-2.1006     1
-0.8519     1
-0.8176     1
-0.4902     1
-0.3143     1
           ..
 24.3164    1
 24.3264    1
 24.3757    1
 24.4149    1
 25.1955    1
Name: target, Length: 113763, dtype: int64
var_61
-48.8027    1
-47.7779    1
-47.6819    1
-47.3058    1
-46.9988    1
           ..
 26.4445    1
 26.5738    1
 26.9009    1
 26.9723    1
 27.1029    1
Name: target, Length: 159369, dtype: int64
var_62
-6.3289    1
-6.1491    1
-6.0988    1
-6.0510    1
-5.9505    1
          ..
 7.3024    1
 7.3825    1
 7.4070    1
 7.6402    1
 7.7536    1
Name: target, Length: 74777, dtype: int64
var_63
-10.5544    1
-10.4517    1
-10.4068    2
-10.2842    1
-10.2766    1
           ..
 9.9711     1
 10.1176    1
 10.3921    1
 10.6380    1
 11.2317    1
Name: target, Length: 97098, dtype: int64
var_64
1.6117     1
1.7240     1
1.7679     1
1.8275     1
1.8490     1
          ..
10.8719    1
10.9404    1
10.9492    1
10.9749    1
11.1537    2
Name: target, Length: 59379, dtype: int64
var_65
-14.0888    1
-13.7212    1
-13.6193    1
-13.4690    1
-12.7267    1
           ..
 13.6304    1
 13.6414    1
 13.9544    1
 14.2107    2
 15.7313    1
Name: target, Length: 108347, dtype: int64
var_66
1.3368    1
1.7539    1
2.0337    1
2.0936    1
2.1184    1
         ..
9.5461    1
9.6029    1
9.6188    1
9.6190    1
9.7132    1
Name: target, Length: 47722, dtype: int64
var_67
-19.5443    1
-17.7479    1
-16.9958    1
-16.8936    1
-16.3353    1
           ..
 37.4376    1
 37.4745    1
 37.8539    1
 39.3056    1
 39.3968    1
Name: target, Length: 137253, dtype: int64
var_68
4.9938    1
4.9951    1
4.9964    1
4.9967    1
4.9976    1
         ..
5.0438    1
5.0444    1
5.0445    1
5.0458    1
5.0469    1
Name: target, Length: 451, dtype: int64
var_69
-16.3094    1
-16.0995    1
-16.0486    1
-15.8873    1
-15.6624    1
           ..
 7.9651     1
 8.1057     1
 8.2595     1
 8.4753     1
 8.5473     1
Name: target, Length: 110346, dtype: int64
var_70
-17.0275    1
-15.9349    1
-15.3447    1
-12.3791    1
-11.5493    2
           ..
 59.9496    1
 60.9406    1
 61.1035    1
 63.3869    1
 64.4644    1
Name: target, Length: 153193, dtype: int64
var_71
-0.2240    1
-0.2201    1
-0.2179    1
-0.1841    1
-0.1583    1
          ..
 1.5074    1
 1.5124    1
 1.5155    1
 1.5354    1
 1.5719    1
Name: target, Length: 13527, dtype: int64
var_72
-12.3834    1
-11.8723    1
-11.5645    1
-11.5538    1
-11.5101    1
           ..
 13.7635    1
 13.8199    1
 13.9879    1
 14.1246    1
 14.1500    1
Name: target, Length: 110114, dtype: int64
var_73
-1.6658     1
-1.1343     1
-1.0664     1
-0.9671     1
-0.8426     1
           ..
 43.4268    1
 43.4961    1
 43.5986    1
 44.2137    1
 44.5361    1
Name: target, Length: 142582, dtype: int64
var_74
-34.1015    1
-32.8139    1
-31.7786    1
-31.6474    1
-31.5289    1
           ..
 67.5137    1
 68.4055    1
 68.5778    1
 69.5024    1
 70.2720    1
Name: target, Length: 161058, dtype: int64
var_75
-1.2936     1
-0.6909     1
-0.6628     1
-0.5288     1
-0.3475     1
           ..
 35.6206    1
 35.6223    1
 35.6242    1
 35.9075    1
 36.1567    1
Name: target, Length: 129383, dtype: int64
var_76
-21.6333    1
-20.9244    1
-20.3150    1
-19.7271    1
-19.3773    1
           ..
 33.0702    1
 33.5674    1
 34.0951    1
 34.4007    1
 34.4352    1
Name: target, Length: 139317, dtype: int64
var_77
7.4257     1
7.7820     2
7.8664     1
8.0724     1
8.4330     2
          ..
30.6091    1
30.6137    1
30.6215    1
30.6240    1
30.9569    1
Name: target, Length: 106809, dtype: int64
var_78
-1.8183     1
-1.2542     1
-0.7483     1
-0.7372     1
-0.6964     1
           ..
 11.2024    1
 11.2183    1
 11.2640    1
 11.3047    2
 11.3507    1
Name: target, Length: 72254, dtype: int64
var_79
10.4454    1
10.4724    1
10.4767    1
10.5191    1
10.5508    1
          ..
18.1112    1
18.1210    1
18.1460    1
18.1787    1
18.2256    1
Name: target, Length: 53212, dtype: int64
var_80
-18.0422    1
-17.0927    1
-16.9501    1
-16.7045    1
-15.8762    1
           ..
 29.1762    1
 29.3029    1
 29.9658    1
 30.2443    1
 30.4769    1
Name: target, Length: 136432, dtype: int64
var_81
7.5865     1
7.5938     1
7.9972     1
8.0189     1
8.0248     1
          ..
22.7227    1
22.8002    1
22.8704    1
22.9300    1
23.1324    1
Name: target, Length: 79065, dtype: int64
var_82
-30.0266    1
-29.8825    1
-29.1308    1
-28.9814    1
-28.7124    1
           ..
 19.2717    1
 19.2787    1
 19.7049    1
 21.2560    1
 21.8934    1
Name: target, Length: 144829, dtype: int64
var_83
-24.2201    1
-22.6955    1
-22.1452    1
-22.0743    1
-21.5471    1
           ..
 26.0673    1
 26.3562    1
 26.6568    1
 26.9660    2
 27.7143    1
Name: target, Length: 144281, dtype: int64
var_84
-24.4398    1
-23.7057    1
-23.3423    1
-23.2112    1
-23.1971    1
           ..
 15.6506    1
 15.6798    1
 16.4966    1
 16.7575    1
 17.7424    1
Name: target, Length: 133766, dtype: int64
var_85
7.0230     1
7.5132     1
7.5869     1
7.6969     1
7.7679     1
          ..
30.0117    1
30.7450    1
30.9763    1
31.0172    1
32.9011    1
Name: target, Length: 108437, dtype: int64
var_86
-19.2722    1
-19.1327    1
-18.1250    1
-17.9972    1
-16.9755    1
           ..
 31.7867    1
 31.8550    1
 33.0470    1
 34.2731    1
 34.5637    1
Name: target, Length: 140594, dtype: int64
var_87
-8.4816     1
-7.9925     1
-7.9873     1
-7.8775     1
-7.3634     1
           ..
 31.6000    1
 32.0732    1
 32.0990    1
 32.7761    1
 33.3541    2
Name: target, Length: 125296, dtype: int64
var_88
1.3502     1
1.5868     1
1.8688     1
1.9595     1
1.9655     1
          ..
16.6540    1
16.7177    1
16.8911    1
17.2686    1
17.4594    1
Name: target, Length: 84918, dtype: int64
var_89
-9.6014     1
-8.5319     1
-8.3123     1
-8.0283     1
-7.9863     1
           ..
 13.8215    1
 13.8636    1
 14.5926    1
 15.1006    1
 15.4816    1
Name: target, Length: 103522, dtype: int64
var_90
-61.7180    1
-60.1899    1
-60.1727    1
-59.7720    1
-59.4043    1
           ..
 21.8372    1
 22.0640    1
 22.4525    1
 22.7534    1
 27.2713    1
Name: target, Length: 157210, dtype: int64
var_91
6.5218    1
6.5222    1
6.5230    1
6.5249    1
6.5321    1
         ..
7.4713    1
7.4794    1
7.4804    1
7.4808    1
7.4895    1
Name: target, Length: 7962, dtype: int64
var_92
-1.0185     1
-0.9188     1
-0.8684     2
-0.1672     1
 0.0269     1
           ..
 26.0624    1
 26.0922    1
 26.1087    1
 26.5581    1
 26.9976    1
Name: target, Length: 110743, dtype: int64
var_93
8.4916     1
8.5204     1
8.5850     1
8.6141     1
8.6235     1
          ..
12.3739    1
12.3911    1
12.4390    1
12.4693    1
12.5343    1
Name: target, Length: 26708, dtype: int64
var_94
2.8190     1
2.9603     1
3.0756     1
3.1070     1
3.1781     1
          ..
18.6461    2
18.6517    1
18.7469    1
18.8107    1
18.9750    1
Name: target, Length: 89146, dtype: int64
var_95
-2.4324    1
-2.4257    1
-2.3331    1
-2.2624    1
-2.2452    1
          ..
 1.7060    1
 1.7107    1
 1.7275    1
 1.7785    1
 1.8040    1
Name: target, Length: 29387, dtype: int64
var_96
-12.1584    1
-12.1539    1
-11.0767    1
-10.8990    1
-10.7929    1
           ..
 40.2641    1
 40.3874    1
 40.4811    1
 40.5045    1
 40.8806    1
Name: target, Length: 148099, dtype: int64
var_97
-21.7400    1
-21.6672    1
-21.1988    1
-21.0126    1
-20.5837    1
           ..
 54.5425    1
 54.6520    1
 56.3333    1
 57.1697    1
 58.2879    1
Name: target, Length: 158739, dtype: int64
var_98
-0.6035    1
-0.4328    1
-0.4137    1
-0.3751    1
-0.3710    1
          ..
 4.2674    1
 4.2687    1
 4.3518    1
 4.4042    1
 4.5028    1
Name: target, Length: 33266, dtype: int64
var_99
-7.2806    1
-7.1508    1
-7.0675    1
-6.9872    1
-6.7723    1
          ..
 4.7659    1
 4.9360    1
 4.9408    1
 4.9939    1
 5.0764    1
Name: target, Length: 69300, dtype: int64
var_100
-39.1791    1
-38.7246    1
-38.5551    1
-38.2927    1
-38.2922    1
           ..
 23.4851    1
 24.2662    1
 24.5254    1
 25.0130    1
 25.1409    1

In [68]:
# case 5
train=train.drop('ID_code', axis=1)
print(train.columns)

Index(['target', 'var_0', 'var_1', 'var_2', 'var_3', 'var_4', 'var_5', 'var_6',
       'var_7', 'var_8',
       ...
       'var_190', 'var_191', 'var_192', 'var_193', 'var_194', 'var_195',
       'var_196', 'var_197', 'var_198', 'var_199'],
      dtype='object', length=201)

In [21]:
# case 6 a
print("std: ",train.std().count())
print("max: ",train.max().count())
print("min: ",train.min().count())
print("mean: ",train.mean().count())
train.describe()

C:\Users\elnur\AppData\Local\Temp\ipykernel_2348\2842876190.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print("std: ",train.std().count())

std:  201
max:  202
min:  202

C:\Users\elnur\AppData\Local\Temp\ipykernel_2348\2842876190.py:5: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print("mean: ",train.mean().count())

mean:  201

,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
count,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,...,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000,200000.000000
mean,0.100490,10.679914,-1.627622,10.715192,6.796529,11.078333,-5.065317,5.408949,16.545850,0.284162,...,3.234440,7.438408,1.927839,3.331774,17.993784,-0.142088,2.303335,8.908158,15.870720,-3.326537
std,0.300653,3.040051,4.050044,2.640894,2.043319,1.623150,7.863267,0.866607,3.418076,3.332634,...,4.559922,3.023272,1.478423,3.992030,3.135162,1.429372,5.454369,0.921625,3.010945,10.438015
min,0.000000,0.408400,-15.043400,2.117100,-0.040200,5.074800,-32.562600,2.347300,5.349700,-10.505500,...,-14.093300,-2.691700,-3.814500,-11.783400,8.694400,-5.261000,-14.209600,5.960600,6.299300,-38.852800
25%,0.000000,8.453850,-4.740025,8.722475,5.254075,9.883175,-11.200350,4.767700,13.943800,-2.317800,...,-0.058825,5.157400,0.889775,0.584600,15.629800,-1.170700,-1.946925,8.252800,13.829700,-11.208475
50%,0.000000,10.524750,-1.608050,10.580000,6.825000,11.108250,-4.833150,5.385100,16.456800,0.393700,...,3.203600,7.347750,1.901300,3.396350,17.957950,-0.172700,2.408900,8.888200,15.934050,-2.819550
75%,0.000000,12.758200,1.358625,12.516700,8.324100,12.261125,0.924800,6.003000,19.102900,2.937900,...,6.406200,9.512525,2.949500,6.205800,20.396525,0.829600,6.556725,9.593300,18.064725,4.836800
max,1.000000,20.315000,10.376800,19.353000,13.188300,16.671400,17.251600,8.447700,27.691800,10.151300,...,18.440900,16.716500,8.402400,18.281800,27.928800,4.272900,18.321500,12.000400,26.079100,28.500700

In [8]:
# case 6 b
var_0=train[train.columns[2]]
print(var_0.mean())

10.679914251999998

In [40]:
# case 7
train[(train.var_0>=train.var_0.min()) & (train.var_0<=train.var_0.mean())].var_0
train.sort_values("var_0").var_0

165885     0.4084
131672     0.4528
10693      0.5979
61234      0.8935
64498      0.9302
           ...
118878    19.7379
180332    19.9984
151150    20.0740
72728     20.3150
101816    20.3150
Name: var_0, Length: 200000, dtype: float64

In [44]:
# case 8
train[(train.var_6>=5) & (train.var_196<=2)].sort_values(["var_6","var_196"])

,ID_code,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
178520,train_178520,0,8.3552,3.1771,14.1615,8.7395,12.6949,-17.0578,5.0000,19.6328,...,3.5216,9.3549,0.1165,11.2583,18.5459,1.4886,-7.8565,9.3376,15.1343,3.9232
96226,train_96226,0,6.9272,-7.2233,9.4582,2.7533,12.7499,-3.4811,5.0000,12.0449,...,0.9883,4.2477,1.0278,3.6318,20.7899,-0.6135,-4.8657,8.1843,18.0433,-7.8859
31358,train_31358,0,6.8633,1.7491,6.9962,9.1567,12.2260,-9.4639,5.0000,13.4335,...,0.9699,12.7298,0.2373,-1.3330,16.6820,1.6500,-2.9644,8.5453,22.1888,-22.8905
144518,train_144518,0,11.1507,1.8899,9.9205,6.3541,11.4973,-17.0949,5.0000,24.1314,...,-0.4442,8.1305,1.5448,1.0222,15.4749,-0.9553,-2.9211,7.8273,16.4830,-10.4016
100155,train_100155,0,15.2324,0.1064,8.1256,5.4908,9.3559,-12.7014,5.0000,14.4801,...,-0.2220,6.9846,0.5477,3.8611,11.9726,0.2048,-1.0909,8.4909,22.0944,-5.6714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145634,train_145634,0,12.1814,-9.5857,10.0422,3.2738,11.3903,-9.7970,8.0629,13.7207,...,-5.2159,8.2479,1.9673,9.2873,16.0583,1.7514,-1.7609,8.9278,17.8620,-6.9081
53930,train_53930,0,6.7664,-1.2567,13.4845,5.3205,8.0738,-2.4524,8.1603,10.3666,...,-3.6728,7.9334,1.7544,7.2069,17.3200,-1.6393,-2.0436,10.2643,17.4915,4.4466
127954,train_127954,0,10.2165,4.0216,8.5107,8.2626,14.4037,-10.1509,8.2106,18.6303,...,4.8182,11.0093,3.1800,3.1932,11.0950,1.1481,0.4267,8.8301,12.3084,4.7323
30682,train_30682,0,10.2401,-0.8734,9.6960,10.2621,12.6482,-8.6782,8.3556,15.1116,...,5.2812,9.2561,3.6894,0.8384,17.0422,-1.2947,-8.9797,10.2965,17.6477,-8.2759
51251,train_51251,0,6.0650,-0.6349,9.4604,10.4442,10.7265,-8.4159,8.4477,13.2452,...,9.2434,8.1815,0.6782,8.6892,19.6113,-1.3452,0.3338,8.8843,17.9751,-3.2101

In [20]:
# case 9
print(train.loc[20000:30000][train.columns[11]])

20000    6.2325
20001    5.4199
20002    8.5767
20003    6.0312
20004    6.8624
          ...
29996    5.9313
29997    8.9955
29998    7.6509
29999    6.4558
30000    6.3307
Name: var_9, Length: 10001, dtype: float64

In [120]:
# case 10 a
features=(train[train.columns[0:12]])
features.corr()

,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,var_9
target,1.000000,0.052390,0.050343,0.055870,0.011055,0.010915,0.030979,0.066731,-0.003025,0.019584,-0.042805
var_0,0.052390,1.000000,-0.000544,0.006573,0.003801,0.001326,0.003046,0.006983,0.002429,0.004962,-0.002613
var_1,0.050343,-0.000544,1.000000,0.003980,0.000010,0.000303,-0.000902,0.003258,0.001511,0.004098,-0.000832
var_2,0.055870,0.006573,0.003980,1.000000,0.001001,0.000723,0.001569,0.000883,-0.000991,0.002648,-0.001932
var_3,0.011055,0.003801,0.000010,0.001001,1.000000,-0.000322,0.003253,-0.000774,0.002500,0.003553,-0.000826
var_4,0.010915,0.001326,0.000303,0.000723,-0.000322,1.000000,-0.001368,0.000049,0.004549,0.001194,-0.000918
var_5,0.030979,0.003046,-0.000902,0.001569,0.003253,-0.001368,1.000000,0.002588,-0.000995,0.000147,-0.005279
var_6,0.066731,0.006983,0.003258,0.000883,-0.000774,0.000049,0.002588,1.000000,-0.002548,-0.001188,-0.005697
var_7,-0.003025,0.002429,0.001511,-0.000991,0.002500,0.004549,-0.000995,-0.002548,1.000000,0.000814,0.002885
var_8,0.019584,0.004962,0.004098,0.002648,0.003553,0.001194,0.000147,-0.001188,0.000814,1.000000,-0.001073
var_9,-0.042805,-0.002613,-0.000832,-0.001932,-0.000826,-0.000918,-0.005279,-0.005697,0.002885,-0.001073,1.000000

In [167]:
# case 10 b 
features.corr().unstack().sort_values(ascending = False)
def unique(list1):
    unique_list = []
    most_correlated=[]
    for x in list1:
        if x not in unique_list:
            unique_list.append(x)
        elif x not in most_correlated:
            most_correlated.append(x)
        else:
            continue
    return(most_correlated)
newList = unique(list(features.corr().unstack().sort_values(ascending = False)))
newList

[1.0,
 0.0667308456127416,
 0.05587034784189922,
 0.052389591771425284,
 0.05034262883427472,
 0.030978627406268906,
 0.01958427090809921,
 0.011055223745083777,
 0.010914638494705474,
 0.0069825488374490935,
 0.006572833797730225,
 0.004962431034879425,
 0.004548885668351456,
 0.0040984875296135705,
 0.003980494188455965,
 0.0038007605240912875,
 0.00355339519673546,
 0.0032577286513737216,
 0.0032533491983441735,
 0.003046247210339282,
 0.002885374243348814,
 0.002648398872313286,
 0.0025877797299055164,
 0.0024999459621498302,
 0.0024290136473742755,
 0.0015689051402917795,
 0.0015111806900299943,
 0.0013258094155350023,
 0.001193621781127098,
 0.0010008601281251833,
 0.000882521113142784,
 0.0008143794737033494,
 0.0007228453981925603,
 0.0003034899499078942,
 0.00014694273462483685,
 4.882528800875086e-05,
 1.0229486236942658e-05,
 -0.0003216973353038753,
 -0.0005436992424820518,
 -0.0007743891803428157,
 -0.000825792020391165,
 -0.0008323169729514585,
 -0.0009017324865577953,
 -0.0009183436430007943,
 -0.0009906045773815204,
 -0.0009949489778342134,
 -0.0010734893475529816,
 -0.0011879949187574756,
 -0.0013681568501258013,
 -0.0019320458226363799,
 -0.002547745516882789,
 -0.002612650154839391,
 -0.003024809556907475,
 -0.005279307072870089,
 -0.005696919408918226,
 -0.04280549959662711]

In [168]:
# case 10 c
newList[0:10]

[1.0,
 0.0667308456127416,
 0.05587034784189922,
 0.052389591771425284,
 0.05034262883427472,
 0.030978627406268906,
 0.01958427090809921,
 0.011055223745083777,
 0.010914638494705474,
 0.0069825488374490935]

In [156]:
# case 11
from pandas.api.types import is_numeric_dtype

low = .05
high = .95
quant_train = train.quantile([low, high])
for name in list(train.columns):
    if is_numeric_dtype(train[name]):
        train = train[(train[name] > quant_train.loc[low, name]) & (train[name] < quant_train.loc[high, name])]
train

Empty DataFrame
Columns: [ID_code, target, var_0, var_1, var_2, var_3, var_4, var_5, var_6, var_7, var_8, var_9, var_10, var_11, var_12, var_13, var_14, var_15, var_16, var_17, var_18, var_19, var_20, var_21, var_22, var_23, var_24, var_25, var_26, var_27, var_28, var_29, var_30, var_31, var_32, var_33, var_34, var_35, var_36, var_37, var_38, var_39, var_40, var_41, var_42, var_43, var_44, var_45, var_46, var_47, var_48, var_49, var_50, var_51, var_52, var_53, var_54, var_55, var_56, var_57, var_58, var_59, var_60, var_61, var_62, var_63, var_64, var_65, var_66, var_67, var_68, var_69, var_70, var_71, var_72, var_73, var_74, var_75, var_76, var_77, var_78, var_79, var_80, var_81, var_82, var_83, var_84, var_85, var_86, var_87, var_88, var_89, var_90, var_91, var_92, var_93, var_94, var_95, var_96, var_97, ...]
Index: []

[0 rows x 202 columns]